version : '2'
services:

  springappserver:
    build:
      context: .
      dockerfile: application.Dockerfile
    ports: 
      - "8080:8080"
    networks:
      - net-spring-db
    volumes:
      - .:/vol/development
    depends_on:
      - sqlite3
      
  sqlite3:
    build:
      context: . 
      dockerfile: sqlite.Dockerfile

networks:
  net-spring-db:
    driver: bridge